version: "3.2"
services:
  student:
    restart: always
    container_name: students_container
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./student_domain
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  scores:
    restart: always
    container_name: scores_container
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:7000"
    build:
      context: ./scores_domain
      dockerfile: Dockerfile
    ports:
      - "7000:7000"

  all_details:
    restart: always
    container_name: all_details_container
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:9000"
    build:
      context: ./all_details_domain
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
