# Generated by Django 4.0.4 on 2022-05-22 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_second_name', models.CharField(max_length=100)),
                ('student_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='female', max_length=12)),
                ('student_roll_number', models.IntegerField()),
            ],
        ),
    ]
