# Generated by Django 4.0.4 on 2022-05-22 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('scores_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student_id', models.UUIDField()),
                ('maths_score', models.IntegerField()),
                ('science_score', models.IntegerField()),
                ('social_sciences_score', models.IntegerField()),
                ('english_score', models.IntegerField()),
                ('second_language_score', models.IntegerField()),
            ],
        ),
    ]
